Add docs for outlier detection step.
spacetelescope/romancal pull request #1042
Opened 2023-12-06 15:31 UTC by mairanteodoro

Resolves [RCAL-503](https://jira.stsci.edu/browse/RCAL-503)

This PR adds the documentation for the outlier detection step.

Successfully ran the regression tests, and the results are available [here](https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/504/).

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [X] updated relevant documentation
- [ ] updated relevant milestone(s)
- [X] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

2023-12-07 14:45 UTC, schlafly reviewed
These look good to me.  There are a few leftover references to JWST that should probably be purged, though it's also probably virtuous to reference that the step's heritage is from Webb.  I forget whether the TSO code remained in the step or not; if not, it probably doesn't belong in the docs.

2023-12-14 19:16 UTC, nden commented
@mairanteodoro What is the status of this? Is it ready to be moved out of Draft status?

2023-12-14 20:10 UTC, mairanteodoro commented
> @mairanteodoro What is the status of this? Is it ready to be moved out of Draft status?

Yes, it is. Thanks for the reminder, @nden!

2023-12-15 14:48 UTC, ddavis-stsci approved these changes
A few, mostly minor comments, but I think it looks good.

2023-12-15 14:48 UTC, ddavis-stsci commented on docs/roman/outlier_detection/main.rst
> +    - all inputs will need to have the same WCS since outlier detection assumes
Can you add links to the step to do this?

2023-12-15 14:48 UTC, ddavis-stsci commented on docs/roman/outlier_detection/main.rst
> +      pixel
I'm not sure that I'd characterize a different distribution of CR as a detector problem.

2023-12-15 14:48 UTC, ddavis-stsci commented on docs/roman/outlier_detection/main.rst
> +    pixels) identified as a statistical outlier.
I'm not sure what you are saying here. Is there special treatment of neighboring pixels or just that outlying pixels will be flagged even is they are neighbors?

2023-12-15 14:48 UTC, ddavis-stsci commented on docs/roman/outlier_detection/outlier_detection_step.rst
> +    Whether the data are being provided in an ASN file or as a list of ASDF filenames,
I'd not use the ASN acronym here and would spell it out as association file and link to the asn_from_list docs. 
https://jwst-pipeline.readthedocs.io/en/latest/jwst/associations/asn_from_list.html

2023-12-15 14:48 UTC, ddavis-stsci commented on docs/roman/outlier_detection/outlier_detection.rst
> +   * The resampling step starts by computing an output WCS that is large enoug
enoug -> enough

2023-12-15 14:48 UTC, ddavis-stsci commented on docs/roman/outlier_detection/outlier_detection.rst
> +     WCS to create a mosaic of all the chips for that exposure.  This product
I think you might mean "All 18 detectors from the same exposure..."?

2023-12-15 14:48 UTC, ddavis-stsci commented on docs/roman/outlier_detection/outlier_detection.rst
> +     and other blemishes, such as satellite trails. Where the difference is larger
I'm not sure how many satellite trails we'll be getting at L2, maybe moving object trails?

2023-12-15 14:48 UTC, ddavis-stsci commented on docs/roman/outlier_detection/outlier_examples.rst
> +                step.process(mc)
Can you add some command line examples?

2023-12-16 13:05 UTC, nden requested changes
The spec section does not render nicely. The problem was solved in the jwst pipeline, see a PR from Brett

2023-12-18 21:07 UTC, mairanteodoro commented
> The spec section does not render nicely. The problem was solved in the jwst pipeline, see a PR from Brett

Done. Applied fix implemented in [PR#8101](https://github.com/spacetelescope/jwst/pull/8101/files).

2023-12-18 21:25 UTC, nden approved these changes

2023-12-19 20:53 UTC, merged