Add unit tests and outlier module refactoring.
spacetelescope/romancal pull request #1058
Opened 2024-01-08 21:20 UTC by mairanteodoro

Resolves [RCAL-502](https://jira.stsci.edu/browse/RCAL-502)

This PR adds unit tests to the newly added outlier detection pipeline module.
The regression test will be added soon.

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [X] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

2024-01-09 12:01 UTC, nden commented on romancal/outlier_detection/tests/test_outlier_detection.py
> +    return model
Why the copy/duplicaiton of this function? Can you call the one in [pointing](https://github.com/spacetelescope/romancal/blob/main/romancal/assign_wcs/pointing.py#L6)?

2024-01-09 12:05 UTC, nden commented on romancal/outlier_detection/tests/test_outlier_detection.py
> +def create_asn_file(tmp_path, members_mapping=None):
This looks like another [code duplicate](https://github.com/spacetelescope/romancal/blob/main/romancal/tweakreg/tests/test_tweakreg.py#L88). Make it a fixture ?

2024-01-09 12:14 UTC, nden commented on romancal/outlier_detection/outlier_detection_step.py
> +        raise TypeError
I don't think raising an error is desirable in this case. It may be better to issue a warning and skip the step.

2024-01-09 12:16 UTC, nden commented on romancal/outlier_detection/outlier_detection_step.py
> +        self.valid_input = len(self.input_models) >= 2 and all(
Is there a need for `valid_input` to be an instance variable, i.e. is `self` necessary here?

2024-01-09 12:32 UTC, nden commented on romancal/outlier_detection/tests/test_outlier_detection.py
> +    step._run_process()
Should `step.process()` be called here to exercise the actual interface?

2024-01-09 12:33 UTC, nden commented on romancal/outlier_detection/tests/test_outlier_detection.py
> +    step.input_models = ModelContainer(asn_filepath)
Is `outlier_detection` supposed to run with associations as input?
If so the handling of the association should be done within the `process` function.

2024-01-09 12:37 UTC, nden commented on romancal/outlier_detection/outlier_detection_step.py
> +                        self.log.debug(f"    {fle}")
Does it make sense to put the code dealing with cleaning of generated files in a separate function?

2024-01-09 13:50 UTC, schlafly requested changes
I may have missed it, but do any of these tests test the ability to detect outliers?  I think you're always sending all-zero images and we should never detect an outlier; in principle we could test that.  It would also be good to set a particular pixel to be high and see if it gets detected, or something?

You also have pretty good control here so I could imagine picking a value for the ivar of the image and the snr parameter and checking that when inserting an outlying pixel that it gets identified at the right snr.  On the other hand, that flows through drizzle & coadding and so might be a bit harder to predict than I'm implying here.  But at least showing that a really obvious outlier gets flagged and that nothing gets flagged when all pixels are the same or consistent with noise or something seems like a test we should definitely have in the outlier detection unit tests?

2024-01-09 20:32 UTC, mairanteodoro commented
> I may have missed it, but do any of these tests test the ability to detect outliers?

Yes, I agree that we should have a test for the detection functionality. That will be added after I have worked on [RCAL-725](https://jira.stsci.edu/browse/RCAL-725), which deals with the actual outlier detection functionality.

2024-01-11 14:51 UTC, schlafly reviewed
Okay, fine with me, but let's wait for Nadia's comments.  And for my two cents, the most important tests are the ones that test something about the core outlier detection algorithm, and not the API around it.  Though of course both are valuable.

2024-01-11 14:51 UTC, schlafly commented on romancal/outlier_detection/tests/test_outlier_detection.py
> +    [x.unlink() for x in Path(os.getcwd()).glob("*.asdf")]
Does this and its relatives feel dangerous?

2024-01-11 17:28 UTC, mairanteodoro commented
> Okay, fine with me, but let's wait for Nadia's comments. And for my two cents, the most important tests are the ones that test something about the core outlier detection algorithm, and not the API around it. Though of course both are valuable.

Agreed.

2024-01-11 18:03 UTC, nden approved these changes
LGTM
Is a regression test in the plans as well, possibly as part of the hlp pipeline?

2024-01-11 18:05 UTC, mairanteodoro commented
> LGTM Is a regression test in the plans as well, possibly as part of the hlp pipeline?

Yes, I will implement the regression test soon after I'm done with RCAL-725, if that's OK.

2024-01-11 18:57 UTC, schlafly approved these changes

2024-01-11 21:58 UTC, merged