RCAL-776: Change image units.
spacetelescope/romancal pull request #1128
Opened 2024-03-06 00:28 UTC by PaulHuwe

Resolves [RCAL-776](https://jira.stsci.edu/browse/RCAL-776)

Closes #1114 #1123 

This PR changed image units in code and tests. Added gain reduction.

NOTE: no regression test link, because these changes require update to regression test files.

**Checklist**
- [x] added entry in `CHANGES.rst` under the corresponding subsection
- [x] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

2024-03-06 12:46 UTC, ddavis-stsci requested changes
This should wait until the rad and roman_datamodels changes are in. We don't really want the pyproject to point to your local branches. 
The code changes look fine.

2024-03-06 15:39 UTC, PaulHuwe commented
> This should wait until the rad and roman_datamodels changes are in. We don't really want the pyproject to point to your local branches. The code changes look fine.

Yeah, they are temporary just for tests to pass. I have updated the Changelog.

2024-03-08 19:03 UTC, schlafly requested changes

2024-03-08 19:03 UTC, schlafly commented on romancal/ramp_fitting/ramp_fit_step.py
> +
Staring at the schema, there is also var_flat, which we don't actually populate or do anything with.  I guess that's a separate ticket.

2024-03-08 20:20 UTC, schlafly commented on romancal/ramp_fitting/ramp_fit_step.py
> +
This is actually fine and I was somehow missing the flat field uncertainty step computation later on.  Disregard this, sorry!

2024-03-11 16:02 UTC, schlafly commented on romancal/ramp_fitting/ramp_fit_step.py
> +
No, the earlier lines do the exact opposite of what you're doing here?  We plan to get rid of the support for the old ramp fitting mode eventually anyway, but I don't see why we should multiply in the gain and then divide it back out without doing any work in the meantime?  Do you see something I'm missing?

2024-03-11 16:24 UTC, PaulHuwe commented on romancal/ramp_fitting/ramp_fit_step.py
> +
Removed.

2024-03-12 12:39 UTC, ddavis-stsci approved these changes
LGTM

2024-03-12 17:00 UTC, merged