Expanded model tests for non reference files.
spacetelescope/romancal pull request #169
Opened 2021-03-03 22:49 UTC by PaulHuwe

2021-03-05 19:11 UTC, eslavich reviewed
The other test that I thought would be useful here is to check that the schema_url attribute refers to a schema that actually exists.  You can check that by calling `asdf.schema.load_schema(model.schema_url)`.

2021-03-10 02:37 UTC, PaulHuwe commented on romancal/datamodels/tests/test_models.py
> +@pytest.mark.parametrize("model_class", list(iter_subclasses(
Schema URL is already teat in lines 24-26.

Other suggested changes implemented.

2021-03-10 13:38 UTC, ddavis-stsci requested changes
You'll need to update the changes file. Looking at it I must have overwritten or messed up the CHANGES.rst from the release. If you could add to the top of the changes file,

```
0.x.0 (unreleased)
==================

datamodels
----------

- Your test text [#169]
```

2021-03-14 20:31 UTC, PaulHuwe commented
Change log updated.

2021-03-16 12:06 UTC, ddavis-stsci requested changes
Looks good. One last thing is that the Changes.rst should also contain the github issue in brackets, so 
`- blah blah blah [#169]`
so that we can track code changes to the issue.

2021-03-16 15:09 UTC, ddavis-stsci approved these changes
LGTM

2021-03-16 15:47 UTC, merged