RCAL-185 Update "dark" step to use STCAL
spacetelescope/romancal pull request #420
Opened 2022-02-03 22:19 UTC by PaulHuwe

… step.

GitHub issue, Closes #271

Resolves [RCAL-185](https://jira.stsci.edu/browse/RCAL-185)

**Description**

This PR updated dark current step to use stcal. Created tests for the updated step.

Regression test updates will be in RCAL-285.

Checklist
- [x] Tests

- [ ] Documentation

- [x] Change log

- [x] Milestone

- [x] Label(s)

2022-02-07 16:10 UTC, ddavis-stsci requested changes
In addition the regression tests are failing for me locally. 
=========================== short test summary info ============================
FAILED ../../../romancal/romancal/regtest/test_dark_current.py::test_dark_current_subtraction_step
FAILED ../../../romancal/romancal/regtest/test_dark_current.py::test_dark_current_outfile_step
FAILED ../../../romancal/romancal/regtest/test_dark_current.py::test_dark_current_outfile_suffix
=========== 3 failed, 13 deselected, 1 xfailed in 700.30s (0:11:40) ============
Are there artifactory updates that need to be done as well?

2022-02-09 16:58 UTC, PaulHuwe commented on romancal/dark_current/tests/test_dark.py
> +    ramp_model.meta.observation.end_time = Time('1922-01-01T11:33:11.110')
The regression tests are addressed in RCAL-285.

2022-02-09 17:07 UTC, PaulHuwe commented on romancal/dark_current/tests/test_dark.py
> +    ramp_model.meta.observation.end_time = Time('1922-01-01T11:33:11.110')
Year updated to 1999

2022-02-09 18:12 UTC, PaulHuwe commented on romancal/dark_current/tests/test_dark.py
> +    ramp.data = np.ones(shape, dtype=np.uint16)
Changed... this was a holdover from a jwst test.

2022-02-09 18:16 UTC, PaulHuwe commented on romancal/dark_current/tests/test_dark.py
> +    ramp.data = np.ones(shape, dtype=np.uint16)
@ddavis-stsci 
There is a line from the step, that I preserved, which reads:

line 46:
input_model.data = input_model.data.astype(np.float32)[np.newaxis, :]

Should I remove that casting, or keep it for safety?

2022-02-09 21:35 UTC, ddavis-stsci commented on romancal/dark_current/tests/test_dark.py
> +    ramp.data = np.ones(shape, dtype=np.uint16)
I'd keep it for safety. My guess is that someone/something managed to trigger it.

2022-02-09 21:41 UTC, ddavis-stsci approved these changes
Looks good

2022-02-10 04:47 UTC, merged