Rcal 65
spacetelescope/romancal pull request #68
Opened 2020-12-07 20:47 UTC by ddavis-stsci

Updated the changes file and removed JWST refs from README

2020-12-07 21:08 UTC, dmggh commented on CHANGES.rst
> +0.0.1 (unreleased)
Should that be 0.0.0 ?

2020-12-07 21:38 UTC, ddavis-stsci commented
I'm assuming that our first build will be 0.0.1 but I'm not sure. I was 
using 0.0.0 as a placeholder.
I should be the same in any case.

On 12/7/20 4:08 PM, dmggh wrote:
>
> *@dmggh* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In CHANGES.rst 
> <https://github.com/spacetelescope/romancal/pull/68#discussion_r537833512>:
>
> > @@ -0,0 +1,11 @@
> +0.0.1 (unreleased)
>
> Should that be 0.0.0 ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/spacetelescope/romancal/pull/68#pullrequestreview-546537210>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ALXCXWPMBF3EPQGV2UWWP5TSTU74NANCNFSM4UQ75RQQ>.
>

2020-12-08 00:04 UTC, sosey requested changes

2020-12-10 21:03 UTC, ddavis-stsci commented
Closing this PR, the changes here were include in PR #70

2020-12-10 21:03 UTC, closed without merging

2020-12-10 21:03 UTC, ddavis-stsci commented
Closing this PR, the changes here were include in PR #70