Add a `pip list` step after the overrides are injected
spacetelescope/romancal pull request #711
Opened 2023-06-05 14:14 UTC by WilliamJamieson

Currently the pip freeze happens after the initial dependency install, but before the OVERRIDE_REQUIREMENTS option is handled by Jenkins. This makes it difficult to see if Jenkins has successfully installed an overriden requirement for the test run. This PR adds an additional `pip list` (same as `pip freeze` just more nicely formatted as a table) after the OVERRIDE_REQUIREMENTS are applied so that one can check in the Jenkins job log to make sure overriden requirements have successfully installed.

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

2023-06-05 15:37 UTC, zacharyburnett requested changes
we can also remove the previous `pip freeze`

2023-06-05 15:37 UTC, zacharyburnett commented on JenkinsfileRT_dev
> +]
```suggestion
bc0.build_cmds = bc0.build_cmds + PipInject(env.OVERRIDE_REQUIREMENTS) + ["pip list"]
```

2023-06-05 15:39 UTC, zacharyburnett commented on JenkinsfileRT_dev
> +bc0.test_cmds = b0.build_cmds + [
```suggestion
bc0.build_cmds = bc0.build_cmds + [
    "pip list"
]
bc0.test_cmds = b0.build_cmds + [
```

2023-06-05 15:56 UTC, zacharyburnett approved these changes
LGTM if the job runs

2023-06-15 22:06 UTC, WilliamJamieson commented
It works just fine, see the list here:
![Screen Shot 2023-06-15 at 6 05 29 PM](https://github.com/spacetelescope/romancal/assets/20687711/2723eb8d-2d47-4e44-8856-2d181e41a246)

2023-06-16 01:32 UTC, WilliamJamieson commented
The regession tests did pass: https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/233/

2023-06-16 01:32 UTC, merged