Actually use the `astropy` nightly wheel.
spacetelescope/romancal pull request #795
Opened 2023-07-26 22:43 UTC by WilliamJamieson

Currently, the Jenkins devdeps job is failing because something on the Jenkins machine has changed enough so that it can no longer build `astropy` wheels natively (some sort of compiler/base-library issue). Unlike the previous attempts at using the `astropy` nightly wheel this PR actually uses that wheel.

Also as a workaround to #793, this PR forces `numpy` 2.0.dev+ versions to use the legacy `numpy` 1.25 floating point (print) representation. Note that this will only work around this issue for the unit tests. ASDF will need to resolve this issue in order to have a general solution.

**Checklist**
- [ ] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

2023-07-26 23:08 UTC, WilliamJamieson commented
Proof that it is now using a prebuilt dev wheel: https://github.com/spacetelescope/romancal/actions/runs/5674451888/job/15378017238#step:10:269

2023-07-26 23:10 UTC, WilliamJamieson commented
This passes the regression tests: https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/298/

Note that I did not run the Roman-devdeps tests on this because that would require me to modify the configuration of that test suite. Instead I modified the Roman-Developers-Pull-Requests job to both point at this version of `romancal` AND use the `JenkinsfileRT_dev` instead of its normal `JenkinsfileRT`.

2023-07-26 23:11 UTC, WilliamJamieson commented on romancal/conftest.py
> +    np.set_printoptions(legacy="1.25")
This has been added only so that the `devdeps` CI and regression tests can be demonstrated to fully work by covering over a known issue in ASDF.

2023-07-26 23:12 UTC, WilliamJamieson commented on requirements-dev.txt
> +--extra-index-url https://pypi.anaconda.org/astropy/simple astropy --pre
The extra-index-url listed in the tox.ini really ought to be moved here.

2023-07-27 12:19 UTC, zacharyburnett approved these changes
LGTM, sorry this has been a runaround for so long. I'll work on removing `--upgrade-strategy eager` as well as that has seemed to cause more problems than its worth

2023-07-27 12:24 UTC, ddavis-stsci requested changes
I think this is a bit premature. If Jenkins is having trouble building astropy wheels shouldn't we file an SPB ticket and if they can't fix it then do the workaround?

2023-07-27 13:10 UTC, WilliamJamieson commented
> I think this is a bit premature. If Jenkins is having trouble building astropy wheels shouldn't we file an SPB ticket and if they can't fix it then do the workaround? 

This is not a work around. Astropy builds a new dev wheel every week or so and uploads it here.

It is my understanding that @nden wanted us to move all the pipeline development testing from building wheels ourselves to using the prebuilt development wheels. I do not think that we should be in the business of attempting to support building libraries that we do not have to.

2023-07-27 13:50 UTC, nden commented
I think the goal is to test working with the latest available dev version of astropy. We can assume they are testing their build system. Let's use the wheels for packages where available to speed up testing, since what we are testing is new functionality changes in dependencies, not their build systems. This is not a new way of running the devdeps tests afaik.

2023-07-27 14:21 UTC, pllim commented
Hi, `astropy` core maintainer here. 👋 

It is my advice that you use the dev wheel that we provide instead of trying to build it yourself. We generate wheels for all the major architectures on versions that we support. If you switch to using our wheel and the system is unable to find one, it might be an indication that you have to upgrade stuff on your end.

In addition, using wheel better reflects how your users will actually run the whole stack. No one sane is going to try to build `astropy` from source downstream because the package has both C-extensions and Cython codes.

Hope this helps!

2023-07-27 17:53 UTC, merged