separate first and third party dev dependencies into requirements.txt files
spacetelescope/romancal pull request #840
Opened 2023-08-21 17:09 UTC by zacharyburnett

This PR splits the dev dependencies into `requirements-dev.txt` and `requirements-dev-thirdparty.txt`

**Checklist**
- [ ] ~added entry in `CHANGES.rst` under the corresponding subsection~
- [ ] ~updated relevant tests~
- [ ] ~updated relevant documentation~
- [ ] updated relevant milestone(s)
- [x] added relevant label(s)

2023-08-21 19:33 UTC, zacharyburnett commented
wait until #843

2023-08-29 17:09 UTC, WilliamJamieson requested changes

2023-08-29 17:09 UTC, WilliamJamieson commented on tox.ini
> +    devdeps: pip install -r requirements-dev-thirdparty.txt -U --upgrade-strategy eager
This should include the `requirements-dev-st.txt` in addition to the third party ones.

2023-09-11 15:36 UTC, zacharyburnett commented on tox.ini
> +    devdeps: pip install -r requirements-dev-thirdparty.txt -U --upgrade-strategy eager
```suggestion
    devdeps: pip install -r requirements-dev-thirdparty.txt -r requirements-dev-st.txt -U --upgrade-strategy eager
```

2023-09-20 12:23 UTC, schlafly approved these changes
Looks good to me, though I'm mostly deferring to the experts!

2023-09-20 19:10 UTC, schlafly commented
@zacharyburnett , can we add a changelog entry and then go ahead and merge this?

2023-09-20 19:19 UTC, ddavis-stsci commented
> @zacharyburnett , can we add a changelog entry and then go ahead and merge this?

The change log is fine but we also need and update to the README.md to explain to the users how to use the new files when installing the software.

2023-09-21 12:44 UTC, zacharyburnett commented on README.md
> +    pip install -r requirements-dev-thirdparty.txt
how is this?

2023-09-21 13:50 UTC, ddavis-stsci approved these changes
LGTM

2023-09-21 16:28 UTC, merged