Filter catalog sources that are outside of the bounding box
spacetelescope/romancal pull request #947
Opened 2023-10-20 22:22 UTC by mcara

Resolves [RCAL-688](https://jira.stsci.edu/browse/RCAL-688)

Closes #926

This PR fixes a bug in the `tweakreg` code due to which full unfiltered source catalog is being passed to `tweakwcs`. This PR makes sure that sources outside of the image's WCS bounding box are removed before the catalog is passed to `tweakwcs`.

**Checklist**
- [x] added entry in `CHANGES.rst` under the corresponding subsection
- [ ] updated relevant tests
- [ ] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)

2023-10-21 01:34 UTC, schlafly approved these changes
Looks good to me, thanks!

2023-10-23 14:16 UTC, mairanteodoro requested changes
Thanks for the catch, @mcara! I have only one comment about the `mask` variable.

2023-10-23 14:16 UTC, mairanteodoro commented on romancal/tweakreg/tweakreg_step.py
> +                )
The variable `mask` was defined inside an `if` statement block and referenced outside of it. Maybe we should move these lines (226-231) into the `if` block?

2023-10-23 18:59 UTC, mairanteodoro commented
@mcara I think you might have to resolve conflicts before pushing your changes.

2023-10-24 13:21 UTC, mairanteodoro approved these changes
Looks good to me! Thanks, @mcara!

2023-10-26 13:42 UTC, schlafly commented
@mcara , any objections to my going ahead and merging this?  @ddavis-stsci , I think with this merged the issue you raised at tag-up should be resolved.

2023-10-26 14:04 UTC, ddavis-stsci commented
I'm not the expert but I don't see an issue. It's approved so go ahead 
at any time.

On 10/26/23 9:42 AM, Eddie Schlafly wrote:
>
> @mcara 
> <https://urldefense.com/v3/__https://github.com/mcara__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2P6ZS2dTxDWeskz1uVu7LP-qwd5T4sb9jXR1MClP_syq6maVzuv_AuXEN_PzD-Et6uZyByXLz-bv4Ksn_3_reOI7$> 
> , any objections to my going ahead and merging this? @ddavis-stsci 
> <https://urldefense.com/v3/__https://github.com/ddavis-stsci__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2P6ZS2dTxDWeskz1uVu7LP-qwd5T4sb9jXR1MClP_syq6maVzuv_AuXEN_PzD-Et6uZyByXLz-bv4Ksn_-90FGMQ$> 
> , I think with this merged the issue you raised at tag-up should be 
> resolved.
>
> —
> Reply to this email directly, view it on GitHub 
> <https://urldefense.com/v3/__https://github.com/spacetelescope/romancal/pull/947*issuecomment-1781155105__;Iw!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2P6ZS2dTxDWeskz1uVu7LP-qwd5T4sb9jXR1MClP_syq6maVzuv_AuXEN_PzD-Et6uZyByXLz-bv4Ksn_6jDi0BT$>, 
> or unsubscribe 
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ALXCXWLB52AIFW2DQFFC33LYBJSFHAVCNFSM6AAAAAA6JUQQNGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBRGE2TKMJQGU__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!2P6ZS2dTxDWeskz1uVu7LP-qwd5T4sb9jXR1MClP_syq6maVzuv_AuXEN_PzD-Et6uZyByXLz-bv4Ksn_0e4GIsg$>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>

2023-10-26 14:26 UTC, merged