replace `pyupgrade` `isort` and `black` with `ruff format`
spacetelescope/romancal pull request #983
Opened 2023-11-08 18:33 UTC by zacharyburnett

This PR replaces the `pre-commit` checks for `pyupgrade`, `isort`, and `black` with  `ruff format`

**Checklist**
- [x] ~added entry in `CHANGES.rst` under the corresponding subsection~
- [x] ~updated relevant tests~
- [x] ~updated relevant documentation~
- [ ] updated relevant milestone(s)
- [x] added relevant label(s)
- [x] ~ran regression tests, post a link to the Jenkins job below. [How to run regression tests on a PR](https://github.com/spacetelescope/romancal/wiki/Running-Regression-Tests-Against-PR-Branches)~

2023-11-09 13:16 UTC, WilliamJamieson commented
In order to actually make this a replacement for all the claimed tools, the rule sets for `isort`, etc have to be enabled in the `pyproject.toml` file. Those are not part of the default rule set.

2023-11-10 14:06 UTC, schlafly approved these changes
This looks fine to me, and I'm probably in favor of fewer moving pieces, which seems to be the goal of this PR.

But I do think we want to ~settle on some choice of code formatting, etc., and not mess with it very often.  Does this represent that choice?

2023-11-10 14:10 UTC, zacharyburnett commented
> This looks fine to me, and I'm probably in favor of fewer moving pieces, which seems to be the goal of this PR.
> 
> But I do think we want to ~settle on some choice of code formatting, etc., and not mess with it very often. Does this represent that choice?

We can configure `ruff format` a bit more than we can Black, namely line length, quote character, indent style, etc.: https://docs.astral.sh/ruff/formatter/#configuration

2023-11-13 14:51 UTC, WilliamJamieson requested changes

2023-11-13 14:51 UTC, WilliamJamieson commented on pyproject.toml
> +[tool.ruff.lint.isort]
This still is not selecting the rules for ruff to replace the pre-commit tooling this PR claims to be replacing. I'll open a PR against your branch fixing these issues.

2025-03-14 16:10 UTC, schlafly commented
I guess it looks like a reviewed this a long time ago and thought it was okay but that I wanted to believe that this would be a stable set of formatting thing for a long time.  Do we think that?  Are we using this in other projects or are we leading the way here?  Broadly, having a common formatting scheme is good but I don't think whatever we have been doing has been causing a lot of problems?

2025-03-18 12:24 UTC, zacharyburnett commented
I don't remember re-requesting a review for this like it says I did, nor for #1522; perhaps this was triggered by a change in automation on GitHub's side. I'll take this back into draft and work more on consolidating rules

2025-03-18 12:27 UTC, zacharyburnett commented
closing as this change has already been implemented

2025-03-18 12:27 UTC, closed without merging